// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgjdiP3PShYgp4_6ewPj2dGKt-i9k_A1s',
    appId: '1:970769932886:web:564051ed89dfb2a82991f7',
    messagingSenderId: '970769932886',
    projectId: 'paycoincust',
    authDomain: 'paycoincust.firebaseapp.com',
    storageBucket: 'paycoincust.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2h5K-jUlqMZbCW9i-X9-HnglvoJLg9Us',
    appId: '1:970769932886:android:a533790feee541bd2991f7',
    messagingSenderId: '970769932886',
    projectId: 'paycoincust',
    storageBucket: 'paycoincust.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAByuCwj9h2evp5gK7doJ55XJ_-5gew_nI',
    appId: '1:970769932886:ios:8c2ec721cdf796912991f7',
    messagingSenderId: '970769932886',
    projectId: 'paycoincust',
    storageBucket: 'paycoincust.appspot.com',
    iosClientId: '970769932886-e77d41fp43noer8vfs1pv958mn5ndddl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sellermultivendor',
  );
}
